# Generated by Django 3.0.10 on 2020-10-13 00:23

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aydin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Keyword')),
            ],
            options={
                'verbose_name': 'EN KeyWords',
                'verbose_name_plural': 'EN Keywords',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='KeywordsTR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Keyword')),
            ],
            options={
                'verbose_name': 'TR KeyWords',
                'verbose_name_plural': 'TR Keywords',
                'ordering': ('-created',),
            },
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ('-created',), 'verbose_name': 'TR Slider ', 'verbose_name_plural': 'TR Sliderlar'},
        ),
        migrations.RemoveField(
            model_name='kvkk',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='kvkk',
            name='bannerimage',
        ),
        migrations.RemoveField(
            model_name='kvkk',
            name='bannertitle',
        ),
        migrations.RemoveField(
            model_name='kvkken',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='kvkken',
            name='bannerimage',
        ),
        migrations.RemoveField(
            model_name='kvkken',
            name='bannertitle',
        ),
        migrations.AddField(
            model_name='kvkk',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Açıklama'),
        ),
        migrations.AddField(
            model_name='kvkk',
            name='titlesite',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Site Başlık'),
        ),
        migrations.AddField(
            model_name='kvkken',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Açıklama'),
        ),
        migrations.AddField(
            model_name='kvkken',
            name='titlesite',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Site Başlık'),
        ),
        migrations.CreateModel(
            name='BlogTr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('banner', models.CharField(max_length=300, verbose_name='Banner Body')),
                ('bannerimage', models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name='Banner Image')),
                ('bannertitle', models.CharField(max_length=200, verbose_name='Banner Title')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlık')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Blog Body')),
                ('image', models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name='Blog Resim')),
                ('slug', models.SlugField(max_length=100)),
                ('titlesite', models.CharField(blank=True, max_length=200, null=True, verbose_name='Site Başlık')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Açıklama')),
                ('keywords', models.ManyToManyField(blank=True, null=True, to='aydin.KeywordsTR', verbose_name='Keywords')),
            ],
            options={
                'verbose_name': 'TR Bloglar ',
                'verbose_name_plural': 'TR Bloglar',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Blog Body')),
                ('image', models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name='Blog Image')),
                ('banner', models.CharField(max_length=300, verbose_name='Banner Body')),
                ('bannerimage', models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name='Banner Image')),
                ('bannertitle', models.CharField(max_length=200, verbose_name='Banner Title')),
                ('slug', models.SlugField(max_length=100)),
                ('titlesite', models.CharField(blank=True, max_length=200, null=True, verbose_name='Site Title')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Description')),
                ('keywords', models.ManyToManyField(blank=True, null=True, to='aydin.Keywords', verbose_name='Keywords')),
            ],
            options={
                'verbose_name': 'EN Blog',
                'verbose_name_plural': 'EN Blogs',
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='kvkk',
            name='keywords',
            field=models.ManyToManyField(blank=True, null=True, to='aydin.Keywords', verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='kvkken',
            name='keywords',
            field=models.ManyToManyField(blank=True, null=True, to='aydin.KeywordsTR', verbose_name='Keywords'),
        ),
    ]
