# Generated by Django 3.0.10 on 2020-10-13 00:34

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aydin', '0002_auto_20201013_0023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kvkk',
            options={'ordering': ('-created',), 'verbose_name': 'TR Aydınlatma Metni ', 'verbose_name_plural': 'TR Aydınlatma Metni'},
        ),
        migrations.CreateModel(
            name='AboutTR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlık')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Hakkımızda Body')),
                ('image', models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name='Hakkımızda Resim')),
                ('slug', models.SlugField(max_length=100)),
                ('titlesite', models.CharField(blank=True, max_length=200, null=True, verbose_name='Site Başlık')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Açıklama')),
                ('keywords', models.ManyToManyField(blank=True, null=True, to='aydin.KeywordsTR', verbose_name='Keywords')),
            ],
            options={
                'verbose_name': 'TR Hakkımızda ',
                'verbose_name_plural': 'TR Hakkımızda',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='About Body')),
                ('image', models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name='About Image')),
                ('slug', models.SlugField(max_length=100)),
                ('titlesite', models.CharField(blank=True, max_length=200, null=True, verbose_name='Site Title')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Description')),
                ('keywords', models.ManyToManyField(blank=True, null=True, to='aydin.Keywords', verbose_name='Keywords')),
            ],
            options={
                'verbose_name': 'EN Hakkımızda',
                'verbose_name_plural': 'EN Hakkımızda',
                'ordering': ('-created',),
            },
        ),
    ]
