# Generated by Django 3.0.10 on 2020-10-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aydin', '0004_homeseo_homeseotr_i̇letisimseo_i̇letisimseotr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iletisim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('body', models.TextField(blank=True, verbose_name='Content')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('tel', models.CharField(max_length=50, verbose_name='Tel')),
            ],
            options={
                'verbose_name': 'TR Mesaj',
                'verbose_name_plural': 'TR Mesajlar',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('body', models.TextField(blank=True, verbose_name='Content')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('tel', models.CharField(max_length=50, verbose_name='Tel')),
            ],
            options={
                'verbose_name': 'EN Mesaj',
                'verbose_name_plural': 'EN Mesajlar',
                'ordering': ('-created',),
            },
        ),
    ]
