# Generated by Django 3.0.10 on 2020-10-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aydin', '0005_iletisim_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSeoPageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Site Başlık')),
                ('image', models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name='Blog Liste Banner')),
                ('titlesite', models.CharField(blank=True, max_length=200, null=True, verbose_name='Site Başlık')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Açıklama')),
                ('keywords', models.ManyToManyField(blank=True, null=True, to='aydin.KeywordsTR', verbose_name='Keywords')),
            ],
            options={
                'verbose_name': 'TR BlogList Page ',
                'verbose_name_plural': 'TR BlogList Page',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='BlogSeoENPageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Site Başlık')),
                ('image', models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name='Blog List Banner')),
                ('titlesite', models.CharField(blank=True, max_length=200, null=True, verbose_name='Site Başlık')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Açıklama')),
                ('keywords', models.ManyToManyField(blank=True, null=True, to='aydin.Keywords', verbose_name='Keywords')),
            ],
            options={
                'verbose_name': 'EN BlogList Page ',
                'verbose_name_plural': 'EN BlogList Page',
                'ordering': ('-created',),
            },
        ),
    ]
