# Generated by Django 3.0.10 on 2020-10-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aydin', '0006_blogseoenpagemodel_blogseopagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvkk',
            name='banner',
            field=models.CharField(blank=True, max_length=300, verbose_name='Banner Body'),
        ),
        migrations.AddField(
            model_name='kvkk',
            name='bannerimage',
            field=models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name='Banner Image'),
        ),
        migrations.AddField(
            model_name='kvkk',
            name='bannertitle',
            field=models.CharField(blank=True, max_length=200, verbose_name='Banner Title'),
        ),
        migrations.AddField(
            model_name='kvkken',
            name='banner',
            field=models.CharField(blank=True, max_length=300, verbose_name='Banner Body'),
        ),
        migrations.AddField(
            model_name='kvkken',
            name='bannerimage',
            field=models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name='Banner Image'),
        ),
        migrations.AddField(
            model_name='kvkken',
            name='bannertitle',
            field=models.CharField(blank=True, max_length=200, verbose_name='Banner Title'),
        ),
    ]
