# Generated by Django 3.0.10 on 2020-10-14 15:10

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aydin', '0007_auto_20201014_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Başlık')),
                ('body', models.FileField(blank=True, upload_to='blogs', verbose_name='Broşür')),
            ],
            options={
                'verbose_name': 'TR Broşür',
                'verbose_name_plural': 'TR Broşürler',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='BrosEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Başlık')),
                ('body', models.FileField(blank=True, upload_to='blogs', verbose_name='Broşür')),
            ],
            options={
                'verbose_name': 'EN Broşür',
                'verbose_name_plural': 'EN Broşürler',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Certifica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Başlık')),
                ('body', models.FileField(blank=True, upload_to='blogs', verbose_name='Sertifika')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CertificaEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Başlık')),
                ('body', models.FileField(blank=True, upload_to='blogs', verbose_name='Sertifika')),
            ],
            options={
                'verbose_name': 'EN Sertifika',
                'verbose_name_plural': 'EN Sertifikalar',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Klavuz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Başlık')),
                ('body', models.FileField(blank=True, upload_to='blogs', verbose_name='Kullanım Klavuzu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KlavuzEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Başlık')),
                ('body', models.FileField(blank=True, upload_to='blogs', verbose_name='Kullanım Klavuzu')),
            ],
            options={
                'verbose_name': 'EN Kullanım Klavuzu',
                'verbose_name_plural': 'EN Kullanım Klavuzları',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ProductsTr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('body', models.TextField(blank=True, verbose_name='Ürün Yazı')),
                ('image', models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name='Ürün Resim')),
                ('image2', models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name='Ürün Resim 2')),
                ('image3', models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name='Ürün Resim 2')),
                ('al_body', models.TextField(blank=True, verbose_name='Özellik 1')),
                ('al_body2', models.TextField(blank=True, verbose_name='Özellik 2')),
                ('al_body3', models.TextField(blank=True, verbose_name='Özellik 3')),
                ('al_body4', models.TextField(blank=True, verbose_name='Özellik 4')),
                ('al_body5', models.TextField(blank=True, verbose_name='Özellik 5')),
                ('tek_body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Teknik Özellikler')),
                ('category', models.CharField(choices=[('DIŞ ORTAM', 'DIŞ ORTAM'), ('İÇ ORTAM', 'İÇ ORTAM'), ('YARDIMCI ÜRÜNLER', 'YARDIMCI ÜRÜNLER')], default='DIŞ ORTAM', max_length=500, verbose_name='Kategori Seçiniz')),
                ('video', embed_video.fields.EmbedVideoField(blank=True)),
                ('slug', models.SlugField(max_length=100)),
                ('titlesite', models.CharField(blank=True, max_length=200, null=True, verbose_name='Site Title')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Description')),
                ('brosur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aydin.Bros', verbose_name='Brosür')),
                ('certifica', models.ManyToManyField(blank=True, null=True, to='aydin.Certifica', verbose_name='Sertifika')),
                ('keywords', models.ManyToManyField(blank=True, null=True, to='aydin.KeywordsTR', verbose_name='Keywords')),
                ('kullanim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aydin.Klavuz', verbose_name='Kullanım Kılavuzu')),
            ],
            options={
                'verbose_name': 'TR Ürün ',
                'verbose_name_plural': 'TR Ürünler',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('body', models.TextField(blank=True, verbose_name='Ürün Yazı')),
                ('image', models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name='Ürün Resim')),
                ('image2', models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name='Ürün Resim 2')),
                ('image3', models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name='Ürün Resim 2')),
                ('al_body', models.TextField(blank=True, verbose_name='Özellik 1')),
                ('al_body2', models.TextField(blank=True, verbose_name='Özellik 2')),
                ('al_body3', models.TextField(blank=True, verbose_name='Özellik 3')),
                ('al_body4', models.TextField(blank=True, verbose_name='Özellik 4')),
                ('al_body5', models.TextField(blank=True, verbose_name='Özellik 5')),
                ('tek_body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Teknik Özellikler')),
                ('category', models.CharField(choices=[('DIŞ ORTAM', 'DIŞ ORTAM'), ('İÇ ORTAM', 'İÇ ORTAM'), ('YARDIMCI ÜRÜNLER', 'YARDIMCI ÜRÜNLER')], default='DIŞ ORTAM', max_length=500, verbose_name='Select Category')),
                ('video', embed_video.fields.EmbedVideoField(blank=True)),
                ('slug', models.SlugField(max_length=100)),
                ('titlesite', models.CharField(blank=True, max_length=200, null=True, verbose_name='Site Title')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Description')),
                ('brosur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aydin.BrosEN', verbose_name='Brosür')),
                ('certifica', models.ManyToManyField(blank=True, null=True, to='aydin.CertificaEN', verbose_name='Sertifika')),
                ('keywords', models.ManyToManyField(blank=True, null=True, to='aydin.Keywords', verbose_name='Keywords')),
                ('kullanim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aydin.KlavuzEN', verbose_name='Kullanım Kılavuzu')),
            ],
            options={
                'verbose_name': 'EN Ürün',
                'verbose_name_plural': 'EN Ürünler ',
                'ordering': ('-created',),
            },
        ),
    ]
