# Generated by Django 3.0.10 on 2020-10-15 08:28

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aydin', '0008_bros_brosen_certifica_certificaen_klavuz_klavuzen_products_productstr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Categori İsmi')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aydin.Category')),
            ],
            options={
                'verbose_name': 'EN Proje Categori',
                'verbose_name_plural': 'EN Proje Categori ',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('tek_body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Proje Açıklama')),
                ('tek_body2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Proje Detay Açıklama')),
                ('image', models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name='Ürün Resim')),
                ('slug', models.SlugField(max_length=100)),
                ('titlesite', models.CharField(blank=True, max_length=200, null=True, verbose_name='Site Title')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Description')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aydin.Category', verbose_name='Select Category')),
                ('keywords', models.ManyToManyField(blank=True, null=True, to='aydin.Keywords', verbose_name='Keywords')),
                ('products', models.ManyToManyField(blank=True, null=True, to='aydin.Products', verbose_name='Products')),
            ],
            options={
                'verbose_name': 'EN Projeler',
                'verbose_name_plural': 'EN Projeler ',
                'ordering': ('-created',),
            },
        ),
    ]
