# Generated by Django 3.0.10 on 2020-10-15 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aydin', '0009_category_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Alt Categori İsmi')),
            ],
            options={
                'verbose_name': 'EN Proje Alt Categori',
                'verbose_name_plural': 'EN Proje Alt Categori ',
                'ordering': ('-created',),
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aydin.SubCategory'),
        ),
    ]
