# Generated by Django 3.0.10 on 2020-10-15 08:38

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aydin', '0010_auto_20201015_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Categori İsmi')),
            ],
            options={
                'verbose_name': 'TR Proje Categori',
                'verbose_name_plural': 'TR Proje Categori ',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='SubCategoryTR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Alt Categori İsmi')),
            ],
            options={
                'verbose_name': 'TR Proje Alt Categori',
                'verbose_name_plural': 'TR Proje Alt Categori ',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ProjectsTR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('tek_body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Proje Açıklama')),
                ('tek_body2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Proje Detay Açıklama')),
                ('image', models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name='Ürün Resim')),
                ('slug', models.SlugField(max_length=100)),
                ('titlesite', models.CharField(blank=True, max_length=200, null=True, verbose_name='Site Title')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Description')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aydin.CategoryTR', verbose_name='Select Category')),
                ('keywords', models.ManyToManyField(blank=True, null=True, to='aydin.KeywordsTR', verbose_name='Keywords')),
                ('products', models.ManyToManyField(blank=True, null=True, to='aydin.ProductsTr', verbose_name='Products')),
            ],
            options={
                'verbose_name': 'TR Projeler',
                'verbose_name_plural': 'TR Projeler ',
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='categorytr',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aydin.SubCategoryTR'),
        ),
    ]
