# Generated by Django 3.0.10 on 2020-10-15 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aydin', '0011_auto_20201015_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorytr',
            name='parent_category',
        ),
        migrations.DeleteModel(
            name='SubCategoryTR',
        ),
    ]
