# Generated by Django 3.0.10 on 2020-10-16 00:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aydin', '0012_auto_20201015_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryTR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Categori İsmi')),
            ],
            options={
                'verbose_name': 'TR Product Alt Categori',
                'verbose_name_plural': 'TR Product Alt Categori ',
                'ordering': ('-created',),
            },
        ),
        migrations.RenameField(
            model_name='productstr',
            old_name='kullanim',
            new_name='dowloads',
        ),
        migrations.RemoveField(
            model_name='productstr',
            name='al_body',
        ),
        migrations.RemoveField(
            model_name='productstr',
            name='al_body2',
        ),
        migrations.RemoveField(
            model_name='productstr',
            name='al_body3',
        ),
        migrations.RemoveField(
            model_name='productstr',
            name='al_body4',
        ),
        migrations.RemoveField(
            model_name='productstr',
            name='al_body5',
        ),
        migrations.RemoveField(
            model_name='productstr',
            name='brosur',
        ),
        migrations.RemoveField(
            model_name='productstr',
            name='certifica',
        ),
        migrations.AlterField(
            model_name='productstr',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Ürün Yazı'),
        ),
    ]
