# Generated by Django 3.0.10 on 2020-10-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aydin', '0013_auto_20201016_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstr',
            name='kod',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ürün Kodu'),
        ),
    ]
