# Generated by Django 3.0.10 on 2020-10-16 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aydin', '0014_productstr_kod'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstr',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aydin.ProductCategoryTR', verbose_name='Alt Kategori'),
        ),
        migrations.AlterField(
            model_name='productstr',
            name='dowloads',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aydin.Klavuz', verbose_name='Dökümanlar'),
        ),
    ]
