# Generated by Django 3.0.10 on 2020-10-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aydin', '0015_auto_20201016_0103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategorytr',
            options={'ordering': ('-created',), 'verbose_name': 'TR Ürünler Alt Categori', 'verbose_name_plural': 'TR Ürünler Alt Categori '},
        ),
        migrations.AddField(
            model_name='projectstr',
            name='image_home',
            field=models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name='Ürün Ana Sayfa Resim'),
        ),
    ]
