# Generated by Django 3.0.10 on 2020-10-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aydin', '0017_auto_20201030_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Slider İsim')),
                ('image', models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name='Ürün Resim')),
            ],
            options={
                'verbose_name': 'Ürün Slider',
                'verbose_name_plural': 'Ürün Sliderları',
            },
        ),
        migrations.AddField(
            model_name='projects',
            name='slider',
            field=models.ManyToManyField(blank=True, null=True, to='aydin.ProjectSlider', verbose_name='Ürün Slider'),
        ),
        migrations.AddField(
            model_name='projectstr',
            name='slider',
            field=models.ManyToManyField(blank=True, null=True, to='aydin.ProjectSlider', verbose_name='Ürün Slider'),
        ),
    ]
