# Generated by Django 3.0.10 on 2020-10-30 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aydin', '0018_auto_20201030_1535'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeSeoTR',
        ),
    ]
