# Generated by Django 3.0.10 on 2020-10-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aydin', '0019_delete_homeseotr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-created',), 'verbose_name': 'TR Proje Categori', 'verbose_name_plural': 'TR Proje Categori '},
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent_category',
        ),
        migrations.AddField(
            model_name='projects',
            name='image_home',
            field=models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name='Ürün Ana Sayfa Resim'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='keywords',
            field=models.ManyToManyField(blank=True, null=True, to='aydin.KeywordsTR', verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='aydin.ProductsTr', verbose_name='Products'),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
