# Generated by Django 3.0.10 on 2020-11-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aydin', '0020_auto_20201031_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsTRSeoTR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('titlesite', models.CharField(blank=True, max_length=200, null=True, verbose_name='Site Title')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Description')),
                ('keywords', models.ManyToManyField(blank=True, null=True, to='aydin.KeywordsTR', verbose_name='Keywords')),
            ],
            options={
                'verbose_name': 'EN SEO Projeler',
                'verbose_name_plural': 'EN SEO Projeler',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ProjectsSeoTR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('titlesite', models.CharField(blank=True, max_length=200, null=True, verbose_name='Site Title')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Description')),
                ('keywords', models.ManyToManyField(blank=True, null=True, to='aydin.KeywordsTR', verbose_name='Keywords')),
            ],
            options={
                'verbose_name': 'TR SEO Projeler',
                'verbose_name_plural': 'TR SEO Projeler',
                'ordering': ('-created',),
            },
        ),
    ]
