# Generated by Django 3.0.10 on 2020-11-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aydin', '0021_projectsseotr_projectstrseotr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-created',), 'verbose_name': 'EN Proje Categori', 'verbose_name_plural': 'EN Proje Categori '},
        ),
        migrations.AlterModelOptions(
            name='projectsseotr',
            options={'ordering': ('-created',), 'verbose_name': 'EN SEO Projeler', 'verbose_name_plural': 'EN SEO Projeler'},
        ),
        migrations.AlterModelOptions(
            name='projectstrseotr',
            options={'ordering': ('-created',), 'verbose_name': 'TR SEO Projeler', 'verbose_name_plural': 'TR SEO Projeler'},
        ),
        migrations.AlterField(
            model_name='projects',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='aydin.Products', verbose_name='Products'),
        ),
    ]
