# Generated by Django 3.2 on 2023-03-05 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aydin', '0024_auto_20230304_2313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='i̇letisimseotr',
            options={'ordering': ('-created',), 'verbose_name': ' SEO İletisim', 'verbose_name_plural': ' SEO İletisim'},
        ),
        migrations.AlterModelOptions(
            name='support',
            options={'ordering': ('-created',), 'verbose_name': ' Mesaj', 'verbose_name_plural': ' Mesajlar'},
        ),
        migrations.RemoveField(
            model_name='projectstr',
            name='category',
        ),
        migrations.RemoveField(
            model_name='projectstr',
            name='description',
        ),
        migrations.RemoveField(
            model_name='projectstr',
            name='image_home',
        ),
        migrations.RemoveField(
            model_name='projectstr',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='projectstr',
            name='products',
        ),
        migrations.RemoveField(
            model_name='projectstr',
            name='slider',
        ),
        migrations.RemoveField(
            model_name='projectstr',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='projectstr',
            name='tek_body',
        ),
        migrations.RemoveField(
            model_name='projectstr',
            name='tek_body2',
        ),
        migrations.RemoveField(
            model_name='projectstr',
            name='titlesite',
        ),
    ]
