# Generated by Django 3.2 on 2023-03-05 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aydin', '0026_productstr_fiyat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategorytr',
            options={'ordering': ('-created',), 'verbose_name': ' Ürünler  Kategori', 'verbose_name_plural': ' Ürünler Kategori '},
        ),
        migrations.RemoveField(
            model_name='productstr',
            name='category',
        ),
        migrations.AlterField(
            model_name='productstr',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aydin.productcategorytr', verbose_name=' Kategori'),
        ),
    ]
