# Generated by Django 3.2 on 2023-03-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aydin', '0028_remove_productstr_dowloads'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abouttr',
            options={'ordering': ('-created',), 'verbose_name': '4-Hakkımızda ', 'verbose_name_plural': '4-Hakkımızda'},
        ),
        migrations.AlterModelOptions(
            name='blogseopagemodel',
            options={'ordering': ('-created',), 'verbose_name': '2.1-Blog Seo ', 'verbose_name_plural': '2.1- Blog Seo'},
        ),
        migrations.AlterModelOptions(
            name='blogtr',
            options={'ordering': ('-created',), 'verbose_name': '2-Bloglar ', 'verbose_name_plural': '2-Bloglar'},
        ),
        migrations.AlterModelOptions(
            name='homeseo',
            options={'ordering': ('-created',), 'verbose_name': 'Ana Sayfa Seo', 'verbose_name_plural': 'Ana Sayfa Seo'},
        ),
        migrations.AlterModelOptions(
            name='keywordstr',
            options={'ordering': ('-created',), 'verbose_name': 'Anahtar Kelimeler Seo ', 'verbose_name_plural': 'Anahtar Kelimeler Seo '},
        ),
        migrations.AlterModelOptions(
            name='kvkk',
            options={'ordering': ('-created',), 'verbose_name': ' Aydınlatma Metni ', 'verbose_name_plural': ' Aydınlatma Metni'},
        ),
        migrations.AlterModelOptions(
            name='productstr',
            options={'ordering': ('-created',), 'verbose_name': '1-Ürün ', 'verbose_name_plural': '1-Ürünler'},
        ),
        migrations.AlterModelOptions(
            name='projectstr',
            options={'ordering': ('-created',), 'verbose_name': 'Galeri', 'verbose_name_plural': 'Galeri '},
        ),
        migrations.AlterModelOptions(
            name='projectstrseotr',
            options={'ordering': ('-created',), 'verbose_name': 'SEO Galeri', 'verbose_name_plural': 'TR SEO Projeler'},
        ),
        migrations.AlterModelOptions(
            name='support',
            options={'ordering': ('-created',), 'verbose_name': '3-Mesaj', 'verbose_name_plural': '3-Mesajlar'},
        ),
        migrations.RemoveField(
            model_name='abouttr',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='productstr',
            name='video',
        ),
        migrations.AlterField(
            model_name='homeseo',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Açıklama'),
        ),
        migrations.AlterField(
            model_name='homeseo',
            name='keywords',
            field=models.ManyToManyField(blank=True, null=True, to='aydin.Keywords', verbose_name='Anahtar Kelimeler'),
        ),
        migrations.AlterField(
            model_name='homeseo',
            name='titlesite',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Site Başlık'),
        ),
        migrations.AlterField(
            model_name='keywordstr',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Anahtar Kelime'),
        ),
        migrations.AlterField(
            model_name='support',
            name='body',
            field=models.TextField(blank=True, verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='support',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Ad Soyad'),
        ),
        migrations.AlterField(
            model_name='support',
            name='tel',
            field=models.CharField(max_length=50, verbose_name='Telefon'),
        ),
    ]
