# Generated by Django 3.2 on 2023-03-05 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aydin', '0029_auto_20230305_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ('-created',), 'verbose_name': '0-Slider ', 'verbose_name_plural': '0-liderlar'},
        ),
        migrations.RemoveField(
            model_name='slider',
            name='button',
        ),
    ]
