# Generated by Django 3.2 on 2023-03-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aydin', '0030_auto_20230305_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogseopagemodel',
            options={'ordering': ('-created',), 'verbose_name': 'Blog Seo ', 'verbose_name_plural': 'Blog Seo'},
        ),
        migrations.AlterModelOptions(
            name='i̇letisimseotr',
            options={'ordering': ('-created',), 'verbose_name': 'İletisim Seo', 'verbose_name_plural': 'İletisim Seo'},
        ),
        migrations.AlterModelOptions(
            name='projectstr',
            options={'ordering': ('-created',), 'verbose_name': '5-Galeri', 'verbose_name_plural': '5-Galeri '},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ('-created',), 'verbose_name': '0-Slider ', 'verbose_name_plural': '0-Sliderlar'},
        ),
        migrations.AddField(
            model_name='productcategorytr',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Description'),
        ),
    ]
