# Generated by Django 3.2 on 2023-03-21 20:08

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aydin', '0031_auto_20230321_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategorytr',
            options={'ordering': ('-created',), 'verbose_name': ' 1.1-Ürünler  Kategori', 'verbose_name_plural': '1.1-Ürünler Kategori '},
        ),
        migrations.AlterField(
            model_name='productcategorytr',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Meta Description'),
        ),
    ]
