# Generated by Django 3.2 on 2023-03-21 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aydin', '0032_auto_20230321_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstr',
            name='slider',
        ),
    ]
