# Generated by Django 3.2 on 2023-03-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aydin', '0033_remove_productstr_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategorytr',
            name='ordering',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
