# Generated by Django 3.2 on 2023-03-22 18:41

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aydin', '0034_productcategorytr_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='İsim')),
                ('name1', models.CharField(max_length=200, verbose_name='Görevi')),
                ('image', models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name=' Resim')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Detaylı Bilgi')),
                ('ordering', models.PositiveIntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'verbose_name': ' 6-Ekibimiz',
                'verbose_name_plural': '6- Ekibimiz',
                'ordering': ('ordering',),
            },
        ),
        migrations.AlterModelOptions(
            name='productcategorytr',
            options={'ordering': ('ordering',), 'verbose_name': ' 1.1-Ürünler  Kategori', 'verbose_name_plural': '1.1-Ürünler Kategori '},
        ),
        migrations.AlterField(
            model_name='productcategorytr',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name=' Açıklama'),
        ),
    ]
