# Generated by Django 3.2 on 2023-03-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aydin', '0035_auto_20230322_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategorytr',
            name='image',
            field=models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name=' Resim'),
        ),
    ]
